### ISSUE TITLE
ライセンスを決める

### ISSUE THREAD

**Issue by zembutsu** [zembutsu/docs.docker.jp#1]
出来るだけ制限をかけず、参照・再利用しやすいライセンスにする。予定。

**Comment by henrich** [comment]
いい試みですね。
ただ、翻訳物は改変に当たるので、upstreamのドキュメントのライセンスを引き継ぐことになります。独自のライセンスは別途許可を得ない限り適用できません。

**Comment by zembutsu** [comment]
ありがとうございます。
https://github.com/docker/docs-base/blob/master/LICENSE
こちらをそのまま使おうと思います。
