### ISSUE TITLE
PDF ダウンロードについて

### ISSUE THREAD

**Issue by nes2002059** [zembutsu/docs.docker.jp#110]
Docker ドキュメント日本語版 PDF ダウンロードが「HTTP 403 アクセス不可」エラーとなりダウンロードできないのですが、アクセス制限等あるのでしょうか。

**Comment by zembutsu** [comment]
ご連絡ありがとうございます。制限はアリマセンが、最近のアクセス増のためサーバを移転したのですが、その際に設定漏れがあった模様です。設定情報を確認します。

**Comment by zembutsu** [comment]
お待たせいたしました。
サーバ側の設定を見直し、PDFをダウンロードできるように調整いたしましたので、ご確認をお願いいたします。
