### ISSUE TITLE
一部欠落している箇所がありました

### ISSUE THREAD

**Issue by websvc** [zembutsu/docs.docker.jp#145]
[Docker CE のインストール](http://docs.docker.jp/engine/installation/linux/docker-ce/centos.html) 以下の、CentOS 用 Docker CE の入手ページ以降を拝見しながらセットアップを行っていて気づいたのですが、日本語訳ページでは、原文の下記の部分が欠落しているようです。

1．Use the following command to set up the stable repository. You always need the stable repository, even if you want to install builds from the edge or test repositories as well.

``
$ sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo>
``

[原文のURL](https://docs.docker.com/engine/installation/linux/docker-ce/centos/#install-docker-ce)

素晴らしい成果物を公開して下さっている事を感謝いたします。

**Comment by zembutsu** [comment]
@websvc ご指摘ありがとうございます 🙇 
多少ページ、原文と他にも差違がわかりましたので、追加しようと思います。

**Comment by zembutsu** [comment]
更新とページの反映が終わりましたので、クローズします 😊
