### ISSUE TITLE
webサイト側のDocoker概要ページにtypoが残っている

### ISSUE THREAD

**Issue by inkusu** [zembutsu/docs.docker.jp#153]
◾️サイトのページURL
[http://docs.docker.jp/engine/docker-overview.html#docker-architecture](http://docs.docker.jp/engine/docker-overview.html#docker-architecture)

該当箇所
> gh Docker はクライアント・サーバ型のアーキテクチャです。

**Comment by zembutsu** [comment]
ご指摘ありがとうございました。ページ再生成済みの現在では、問題箇所の確認ができなかったため、close とさせていただきます。
