### ISSUE TITLE
typo: docker-hub/builds.rst

### ISSUE THREAD

**Issue by osamu0329nakamura** [zembutsu/docs.docker.jp#154]
以下のドキュメントにちょっとしたtypoがあります。

http://docs.docker.jp/docker-hub/builds.html

- 誤：コード *画* 変更されると、リポジトリも自動的に更新されます。
- 正：コードが変更されると、リポジトリも自動的に更新されます。

**Comment by kmiura-1002** [comment]
typoを修正してしました。
確認お願いいたします。

**Comment by zembutsu** [comment]
Merge いたしましたので、本件 close とさせていただきます。
