### ISSUE TITLE
コンテナでデータをするのリードオンリーのオプション指定がおそらく間違い

### ISSUE THREAD

**Issue by TsuyoshiUshio** [zembutsu/docs.docker.jp#19]
翻訳
[コンテナでデータを管理する](https://github.com/zembutsu/docs.docker.jp/blob/master/engine/userguide/dockervolumes.rst)

英語
[Manage data in containers](https://docs.docker.com/engine/userguide/dockervolumes/)

この記事の
```
$ docker run -d -P --name web -v /opt/webapp:ro training/webapp python app.py
```

は実際には

```
$ docker run -d -P --name web --read-only -v /opt/webapp training/webapp python app.py
```

ではないかと思われます。

[run](https://docs.docker.com/engine/reference/commandline/run/) mount volume 参照

**Comment by zembutsu** [comment]
挙動を確認します。
