### ISSUE TITLE
LXC support removed

### ISSUE THREAD

**Issue by znz** [zembutsu/docs.docker.jp#25]
http://docs.docker.jp/engine/understanding-docker.html#id22 に「Docker は LXC を使う伝統的な Linux コンテナもサポートしています。」とありますが、 https://github.com/docker/docker/releases/tag/v1.10.0 の Deprecations で「Remove LXC support.」と書いてあり、 https://docs.docker.com/engine/understanding-docker/ でも LXC の記述は消えているようです。

**Comment by zembutsu** [comment]
ありがとうございます。ドキュメントが古いままのため、変更対応予定です。

**Comment by zembutsu** [comment]
更新しましたので、クローズします :smiley:
