### ISSUE TITLE
sphinxリンク切れに関する報告およびメモ

### ISSUE THREAD

**Issue by zembutsu** [zembutsu/docs.docker.jp#279]
- rest の `:doc:` や `:ref:` でリンク切れを把握している場合、後日対応するためのメモです
- Sphinx で `make html` 実行時に warning が発生しているのは認識しています。有る程度ドキュメントがまとまってきた段階で、まとめて対応予定です
---
- [ ] #270

**Comment by revsystem** [comment]
修正方法がよくわからなかったのでこちらにコメントを残します。
http://docs.docker.jp/get-started/index.html で get-started.png へのリンクが切れています。
https://github.com/zembutsu/docs.docker.jp/edit/master/get-started/index.rst では表示されておりリポジトリ上にも画像ファイルがあるようです。

@zembutsu

**Comment by zembutsu** [comment]
@revsystem ご指摘ありがとうございました。画像が表示されるように作業済みです。
ウェブサーバ上に画像ファイルがなかったのが原因でした。

**Comment by revsystem** [comment]
リンク切れではないのですが、https://github.com/zembutsu/docs.docker.jp/blob/master/engine/userguide/networking/default_network/binding.rst がサイトに反映されていないようです。
サイト上は`--ip=IP_ADDRESS オプションをツイ買います。`となっていますが、masterでは修正されていました。

@zembutsu

**Comment by revsystem** [comment]
https://github.com/zembutsu/docs.docker.jp/blob/master/docker-for-mac/multi-arch.rst もmasterがサイトに反映されていないようです。
サイト上では、`アーキテクチャの角煮もできます。`となっていますが、masterでは修正されていました。

@zembutsu

**Comment by zembutsu** [comment]
@revsystem ご連絡ありがとうございます、確認の上本番環境に反映しておきました。ありがとうございました。
http://docs.docker.jp/get-started/index.html
http://docs.docker.jp/docker-for-mac/multi-arch.html
