### ISSUE TITLE
誤記の報告@engine/swarm/key-concepts.rst 

### ISSUE THREAD

**Issue by tykep** [zembutsu/docs.docker.jp#289]
日本語ドキュメントの整備いつもありがとうございます。
標題のドキュメントにて小さい誤記を１つ見つけたので、報告させてもらいます。

ノード（nodes）の章にて
`warker ノード（worker nodes）`

試しにリポジトリ全体を全文検索してみましたが「warker」が出てたのはコレ１つでした。

**Comment by zembutsu** [comment]
@tykep ご指摘ありがとうございます。typoですので修正しておきます。

**Comment by zembutsu** [comment]
https://github.com/zembutsu/docs.docker.jp/pull/291
こちらで反映しておきました。ありがとうございました。
