### ISSUE TITLE
docker runコマンドで -d と --rmが一緒に指定できるようになっている

### ISSUE THREAD

**Issue by kazuseki** [zembutsu/docs.docker.jp#363]
### 概要

docker runコマンドのオプション

- Detached (`-d`)
- Clean up (`--rm`)

について、以前は一緒に指定できなかったのが、できるようになっています。
Docker run リファレンスの修正が必要と思います。

### 日本語の対象ファイル

https://github.com/zembutsu/docs.docker.jp/blob/master/engine/reference/run.rst

対象部

```
コンテナをデタッチド・モードで起動するには、 ``-d=true`` か ``-d`` オプションを使います。
設計上、コンテナが実行するルート・プロセスが終了したら、デタッチド・モードで起動したコンテナも終了します。
デタッチド・モードのコンテナは停止しても自動的に削除できません。
つまり ``-d`` オプションでは ``--rm`` を指定できません。
```

### 元の英文ファイルで更新済みの箇所

https://github.com/docker/cli/blob/master/docs/reference/run.md

```
To start a container in detached mode, you use -d=true or just -d option.
By design, containers started in detached mode exit when the root process used to run the container exits, unless you also specify the --rm option.
If you use -d with --rm, the container is removed when it exits or when the daemon exits, whichever happens first.
```

### 変更が入ったコミット

[4 Jul 2017 - Clarify that you can use -d and --rm together now](https://github.com/docker/cli/commit/c63485b47d40dd22b68fe8f509637a7327330422)

間違った認識でissueを上げていたらすみません。

**Comment by zembutsu** [comment]
ご指摘ありがとうございます。
GitHub 上では反映前ですが、ローカルのリポジトリとサイト上の情報は更新いたしました。
http://docs.docker.jp/engine/reference/run.html#d
