### ISSUE TITLE
ベストプラクティス/ENTRYPOINT の項のリンクが誤っている

### ISSUE THREAD

**Issue by mollinaca** [zembutsu/docs.docker.jp#365]
https://docs.docker.jp/engine/articles/dockerfile_best-practice.html#entrypoint にあるリンク部分
[Dockerfile リファレンスの ENTRYPOINT 命令] のリンクのURLが誤っています。

[誤] ※現在の状態
https://docs.docker.jp/engine/reference/builder.html#copy

[正]
https://docs.docker.jp/engine/reference/builder.html#entrypoint

**Comment by zembutsu** [comment]
ご指摘ありがとうございます。
