### ISSUE TITLE
「する」が「すr」となっている

### ISSUE THREAD

**Issue by marufura** [zembutsu/docs.docker.jp#376]
[Dockerfile のベストプラクティス](https://docs.docker.jp/engine/articles/dockerfile_best-practice.html) の2段落目に

> このドキュメントは Docker 社が推奨するベストプラクティスや手法を扱っており、Docker コミュニティが簡単かつ効率的に Dockerfile を作成できるようにします。この推奨方法に従うことを強く勧めます（実際、公式イメージを作成すｒには、これらのプラクティスに従う 必要 があります）。

という項目について「する」が「すr」となっている誤字がありました。

**Comment by zembutsu** [comment]
@marufura  ご指摘ありがとうございました。該当ページは修正しておきました。
なお、新しいバージョンのページもありますので、新たにリンクも追加しておきました。
現行バージョンについては、こちらもあわせてご覧下さい。
http://docs.docker.jp/develop/develop-images/dockerfile_best-practices.html
