### ISSUE TITLE
オリジナル記事のURLがあったら便利かも

### ISSUE THREAD

**Issue by kujiy** [zembutsu/docs.docker.jp#40]
素敵なドキュメントをありがとうございます。素晴らしい翻訳に驚きました。私も時間ができたらお手伝いさせていただきたいなと思います。その前に、読んでいてひとつ感じたことを。

記事のどこかにオリジナル記事へのURLがあると、読む人も翻訳者も便利かなと思います。（私が見つけれていないだけ？）
ToDoのページも、オリジナルページに飛べるとコマンドだけでも見れたりするので英語が読めない人も多少は助かるかと思います。

いかがでしょうか。

**Comment by zembutsu** [comment]
ご提案ありがとうございます。
そうですね、実は URL を docks.docker.com と対応させているのですが、
たしかにあったほうが良いですね！

各ページの一番下か、あるいは右上のあたりでしょうか。

**Comment by kujiy** [comment]
翻訳者的には右上も欲しいですけど、記事の終わりでいいんじゃないでしょうか。

既に素敵なレイアウト・構成になっているので、 @zembutsu さんのセンスがベストだと思います :smiley:

**Comment by zembutsu** [comment]
恐縮です。そうですね、文末でしたら `.. seealso::` という reSt の命令を使えばページの収まりも良さそうです。ちょうど Swarm まわりを見直しているところなので、試験的に反映してみようと思います。

**Comment by kujiy** [comment]
:+1:

**Comment by zembutsu** [comment]
一通り追加しましたので、本件クローズします。
