### ISSUE TITLE
typo: できｍさう

### ISSUE THREAD

**Issue by shakiyam** [zembutsu/docs.docker.jp#416]
[イメージ検査のベストプラクティス](https://docs.docker.jp/develop/scan-images/index.html )にtypoらしきものがあります。
> Docker Hub を通した脆弱性検査、表示、調査のトリガを設定できｍさう。詳しい情報は、 Hub 脆弱性検査 をご覧ください。

**Comment by zembutsu** [comment]
ご指摘ありがとうございます。
