### ISSUE TITLE
チュートリアルのbuildで失敗する

### ISSUE THREAD

**Issue by monami12** [zembutsu/docs.docker.jp#419]
https://docs.docker.jp/get-started/02_our_app.html

# syntax=docker/dockerfile:1
FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000

だと動きません。

FROM node:18-alpine
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]

で動きました。

**Comment by zembutsu** [comment]
ご指摘ありがとうございます。
